<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>ajax.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>debug.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>event.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>template.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>types.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>i18n.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>node.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>format.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>state.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>string.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>adapters/jquery-ui.js"></script>
<script type="text/javascript" src="<?= RAPTOR_COMMON_URI; ?>adapters/pnotify.js"></script>
